import { execFile } from 'node:child_process';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { promisify } from 'node:util';
import { describe, expect, it } from 'vitest';

const execFileAsync = promisify(execFile);
const root = resolve(import.meta.dirname, '../..');
const script = resolve(root, 'scripts/release-evidence-preflight.mjs');

function report() {
  return {
    schema: 'llm-chat-history/live-qa-report',
    schemaVersion: 1,
    generatedAt: '2026-09-16T12:00:00.000Z',
    extensionVersion: '0.1.0',
    providerId: 'chatgpt',
    route: {
      kind: 'home',
      pathSegmentCount: 0,
      queryPresent: false,
      hashPresent: false,
      providerConversationIdPresent: false,
      provisional: true
    },
    dom: {
      selectors: {
        sectionUserTurns: 0,
        sectionAssistantTurns: 0,
        articleTurns: 0,
        userRoleNodes: 0,
        assistantRoleNodes: 0,
        turnIdNodes: 0,
        messageIdNodes: 0,
        conversationTurnTestIds: 0,
        collapsibleUserContent: 0,
        markdownWrappers: 0,
        proseWrappers: 0,
        conversationLinks: 0
      },
      stopGenerationControlPresent: false,
      adapterScrollContainerFound: true,
      adapterUsesDocumentScrollingElement: false,
      mobileAppShellScrollContainerPresent: true,
      historyApiAvailable: true
    },
    runtime: {
      adapterState: 'healthy',
      adapterCode: 'ready',
      recordingState: 'recording',
      storageHealth: 'healthy',
      renderedTurnCount: 0,
      lastSaveConfirmed: true,
      historicalImportAvailable: false
    },
    archive: {
      conversationFound: false,
      messageCount: 0,
      eventCount: 0,
      recordingState: null
    },
    privacy: {
      containsChatText: false,
      containsRawUrl: false,
      containsConversationTitle: false,
      containsProviderConversationId: false
    }
  };
}

function session() {
  return {
    schema: 'llm-chat-history/release-qa-session',
    schemaVersion: 1,
    candidate: {
      commitSha: '9ec6054c7d68d91ef2dc6e22e0fa297d0788a445',
      version: '0.1.0',
      unpackedArtifact: 'llm-chat-history-unpacked-example',
      unpackedArtifactSha256: 'a'.repeat(64),
      packagedArtifactSha256: 'b'.repeat(64),
      ciRunId: 35096505521
    },
    environment: {
      browser: 'Chrome',
      browserVersion: '152.0.0.0',
      os: 'Test OS'
    },
    testedAt: '2026-09-16T12:00:00.000Z',
    tester: 'QA Tester',
    scenarios: Array.from({ length: 10 }, (_, index) => ({
      id: index + 1,
      status: 'PASS',
      reports: ['report.json'],
      notes: ''
    }))
  };
}

async function evidenceDir() {
  const directory = await mkdtemp(resolve(tmpdir(), 'llmch-release-evidence-'));
  await writeFile(resolve(directory, 'report.json'), JSON.stringify(report()), 'utf8');
  await writeFile(resolve(directory, 'qa-session.json'), JSON.stringify(session()), 'utf8');
  return directory;
}

async function run(directory) {
  return execFileAsync(process.execPath, [script, '--evidence', directory], { cwd: root });
}

describe('release QA evidence preflight', () => {
  it('accepts a complete ten-scenario structurally valid evidence bundle', async () => {
    const directory = await evidenceDir();
    const result = await run(directory);
    expect(result.stdout).toContain('Release QA preflight PASS: 10 scenarios, 10 report(s)');
    const summary = await readFile(resolve(directory, 'release-qa-preflight.md'), 'utf8');
    expect(summary).toContain('Scenario 10: PASS');
    expect(summary).toContain('9ec6054c7d68d91ef2dc6e22e0fa297d0788a445');
  });

  it('rejects a report with unexpected fields', async () => {
    const directory = await evidenceDir();
    const invalid = { ...report(), leakedPrompt: 'must never be accepted' };
    await writeFile(resolve(directory, 'report.json'), JSON.stringify(invalid), 'utf8');
    await expect(run(directory)).rejects.toMatchObject({ stderr: expect.stringContaining('unexpected field: leakedPrompt') });
  });

  it('rejects incomplete human scenario approval', async () => {
    const directory = await evidenceDir();
    const invalid = session();
    invalid.scenarios[4].status = 'BLOCKED';
    await writeFile(resolve(directory, 'qa-session.json'), JSON.stringify(invalid), 'utf8');
    await expect(run(directory)).rejects.toMatchObject({ stderr: expect.stringContaining('Scenario 5 is not PASS') });
  });

  it('rejects evidence generated by a different extension version', async () => {
    const directory = await evidenceDir();
    const invalid = report();
    invalid.extensionVersion = '0.2.0';
    await writeFile(resolve(directory, 'report.json'), JSON.stringify(invalid), 'utf8');
    await expect(run(directory)).rejects.toMatchObject({ stderr: expect.stringContaining('does not match 0.1.0') });
  });
});
